services:
  # =========================
  # NGINX (REVERSE PROXY)
  # =========================
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ojs
      - dashboard
    networks:
      - appnet

  # =========================
  # OJS DATABASE (MySQL)
  # =========================
  ojs-db:
    image: mysql:8.0
    container_name: ojs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ojs
      MYSQL_USER: ojsuser
      MYSQL_PASSWORD: ojs123
    volumes:
      - ojs_db_data:/var/lib/mysql
    networks:
      - appnet

  # =========================
  # OJS SERVER
  # =========================
  ojs:
    image: pkpofficial/ojs:3_5_0-3
    container_name: ojs-app
    restart: always
    depends_on:
      - ojs-db
    environment:
      DATABASE_HOST: ojs-db
      DATABASE_NAME: ojs
      DATABASE_USER: ojsuser
      DATABASE_PASSWORD: ojs123
    volumes:
      - ./ojs-files:/var/www/html/files
    networks:
      - appnet

  # =========================
  # SCANNER DB (MongoDB)
  # =========================
  scanner-db:
    image: mongo:6
    container_name: mongo-scanner
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  # =========================
  # SCANNER SERVICE
  # =========================
  scanner:
    build: ./scanner
    container_name: scanner-service
    restart: always
    depends_on:
      - ojs
      - scanner-db
    environment:
      OJS_URL: http://ojs
      MONGO_URI: mongodb://scanner-db:27017
    networks:
      - appnet

  # =========================
  # RISK ENGINE SERVICE
  # =========================
  risk-engine:
    build: ./risk-engine
    container_name: risk-engine-service
    restart: always
    depends_on:
      - scanner
    environment:
      SCANNER_URL: http://scanner:5000
    networks:
      - appnet

  # =========================
  # DASHBOARD (Laravel)
  # =========================
  dashboard:
    build: ./dashboard
    container_name: laravel-dashboard
    restart: always
    depends_on:
      - risk-engine
    networks:
      - appnet

# =========================
# VOLUMES
# =========================
volumes:
  ojs_db_data:
  mongo_data:

# =========================
# NETWORK
# =========================
networks:
  appnet:
