services:
  # OJS DATABASE (MySQL)
  ojs-db:
    image: mysql:8.0
    container_name: ojs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ojs
      MYSQL_USER: ojsuser
      MYSQL_PASSWORD: ojs123
    volumes:
      - ojs_db_data:/var/lib/mysql
    networks:
      - appnet

  # OJS SERVER
  ojs:
    image: pkpofficial/ojs:3_5_0-3
    container_name: ojs-app
    restart: always
    depends_on:
      - ojs-db
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: ojs-db
      DATABASE_NAME: ojs
      DATABASE_USER: ojsuser
      DATABASE_PASSWORD: ojs123
    volumes:
      - ./ojs-files:/var/www/html/files
    networks:
      - appnet

  # SCANNER DB (MongoDB)
  scanner-db:
    image: mongo:6
    container_name: mongo-scanner
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  # SCANNER SERVICE (Python)
  scanner:
    build: ./scanner
    container_name: scanner-service
    restart: always
    depends_on:
      - ojs
      - scanner-db
    environment:
      OJS_URL: http://ojs:80
      MONGO_URI: mongodb://scanner-db:27017
    networks:
      - appnet

  # RISK ENGINE (Python)
  risk-engine:
    build: ./risk-engine
    container_name: risk-engine
    restart: always
    depends_on:
      - scanner-db
    environment:
      MONGO_URI: mongodb://scanner-db:27017
    networks:
      - appnet

  # DASHBOARD (Laravel)
  dashboard:
    build: ./dashboard
    container_name: laravel-dashboard
    restart: always
    depends_on:
      - risk-engine
    ports:
      - "8000:8000"
    networks:
      - appnet

# VOLUMES
volumes:
  ojs_db_data:
  mongo_data:

# NETWORK
networks:
  appnet:
