server {
    listen 80;

    # =========================
    # OJS
    # =========================
    location / {
        proxy_pass http://ojs:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # =========================
    # DASHBOARD
    # =========================
    location /dashboard/ {
        proxy_pass http://dashboard:8000/;
    }

    # =========================
    # SCANNER API
    # =========================
    location /scanner/ {
        proxy_pass http://scanner:5000/;
    }
    
    # =========================
    # RISK-ENGINE API
    # =========================
    location /risk/ {
        proxy_pass http://risk-engine:5000/;
    }
}
